### ISSUE TITLE
Keep README + documentation up-to-date

### ISSUE THREAD

**Issue by arnoBruynseels** [BugBattle/JavaScript-SDK#12]
Version: `"bugbattle": "^3.3.0",`

The README + documentation is not up-to-date with the actual available options in the SDK.

Example:

The README still tells you, you can use custom data using the following option:

![image](https://user-images.githubusercontent.com/11627782/112608163-49009180-8e1a-11eb-9cae-47168d48c2c6.png)

While the actual available option is:

```
BugBattle.attachCustomData({
    test1: 'Battle',
    data2: 'Unicorn',
});
```

**Comment by boehlerlukas** [comment]
@arnoBruynseels thanks a lot for the heads up! I just updated the Readme & Docs.
