### ISSUE TITLE
screenshot capturing does not record modal boxes

### ISSUE THREAD

**Issue by markbreuss** [BugBattle/JavaScript-SDK#5]
Hi there!

First, congrats to the very nice product, we are seeing significant speed up to our bug reporting process!

One issue we recently found is that screenshots from modal boxes are not recorded correctly.
E.g. when a user tried to report the UI bug of the sign in form below, the received screenshot does no show the modal itself.

Actual Screen:
![image](https://user-images.githubusercontent.com/69714845/108547887-5c847e00-72eb-11eb-9b0f-1afc687f653d.png)

Reported Screenshot from Bug Battle:
![76DXEAXt9Hp6k75sE690hoDAqhDjX7](https://user-images.githubusercontent.com/69714845/108548451-2398d900-72ec-11eb-986f-3bbfa0e8a51f.jpg)

Greetings, 

Mark

**Comment by boehlerlukas** [comment]
@markbreuss thanks for your report! We will have a look into it and adjust the library accordingly. This might take a few days. I will update you as soon as we got a fix ready for you!

**Comment by markbreuss** [comment]
@boehlerlukas thanks!

Nice, just changed it - looks great👍.

**Comment by markbreuss** [comment]
Hi @boehlerlukas,

We had a couple of bug reports with modal overlays and they were all recorded correctly.
See example below.

Thanks for the quick fix!

![image](https://user-images.githubusercontent.com/69714845/111367703-49b85b80-8695-11eb-93bc-250bc8e433bb.png)


Cheers, Mark

**Comment by boehlerlukas** [comment]
@markbreuss that's great to hear! Our latest update to the SDK changed the way how the screenshots got rendered. This should drastically improve the whole screenshot quality.

Let me know if you have further questions or requests - we are always here to help!
