### ISSUE TITLE
Feature Request: more characters of the description used for Trello Title

### ISSUE THREAD

**Issue by markbreuss** [BugBattle/JavaScript-SDK#6]
Hi there,

since Trello has almost no limit in regards to title length, it seems pretty harsh to cut the title mid word to 15 char.
See example below.

The way its implemented now, we need to edit each cards title after reporting the bug to get a good overview.
Extending the title limit to either the first Sentence and/or take the first few words could eliminate this "labeling" step.

![image](https://user-images.githubusercontent.com/69714845/108548692-7f636200-72ec-11eb-8a93-728fc0b7d020.png)

Greetings,

Mark

**Comment by boehlerlukas** [comment]
Hey @markbreuss !

Great feature request! This seems totally legit! I just pushed an update for the Trello integration. New cards will now have the whole first sentence as card title. Let me know if that works out for you as expected!

Best regards,
Lukas

**Comment by markbreuss** [comment]
Hi @boehlerlukas,

works great - thanks for the fast change!

-Mark

**Comment by boehlerlukas** [comment]
@markbreuss great to hear! Let us know if you have further feature requests :)
